### ISSUE TITLE
Fix for audit  in terminal madness

### ISSUE THREAD

**Issue by danpopnyc** [krisnova/novix#3]
in boot/cmdline.txt root=/dev/mmcblk0p2 rw rootwait console=ttyAMA0,115200 console=tty1 selinux=0 plymouth.enable=0 smsc95xx.turbo_mode=N dwc_otg.lpm_enable=0 kgdboc=ttyAMA0,115200 elevator=noop **audit=0**

thank you :  https://archlinuxarm.org/forum/viewtopic.php?f=60&t=13175

@kris-nova probably something to update the original image with.  /boot

**Comment by danpopSD** [comment]
also to supress kernel messages in TTY: 

`sudo dmesg -n 1`

**Comment by kris-nova** [comment]
On it!

**Comment by kris-nova** [comment]
Hey @danpopSD can you share how you are making your image? I am unable to replicate this on my end. 

I have heard other reports from using flashing tools like `gdisk` or `etcher` also causing weird terminal output from the Falco kernel module. I am certain I can fix it - if I can just figure out how to replicate.

thank you!

**Comment by danpopSD** [comment]
method of image deployment:  
![image](https://user-images.githubusercontent.com/22457772/80873294-7a61f300-8c85-11ea-989e-01f7c30664bd.png)

using an rpi3.

**Comment by maxgio92** [comment]
The same for me flashing the card with Apple Pi Baker. I’ll dig into how it works Apple Pi Baker because it was a workaround for me
